#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-JQuery.quicksearch
Version  : 2.0.3.1
Release  : 12
URL      : https://pypi.python.org/packages/source/X/XStatic-JQuery.quicksearch/XStatic-JQuery.quicksearch-2.0.3.1.tar.gz
Source0  : https://pypi.python.org/packages/source/X/XStatic-JQuery.quicksearch/XStatic-JQuery.quicksearch-2.0.3.1.tar.gz
Summary  : JQuery.quicksearch 2.0.3 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT
Requires: XStatic-JQuery.quicksearch-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-JQuery.quicksearch
--------------
JQuery.quicksearch JavaScript library packaged for setuptools (easy_install)
/ pip.

%package python
Summary: python components for the XStatic-JQuery.quicksearch package.
Group: Default

%description python
python components for the XStatic-JQuery.quicksearch package.


%prep
%setup -q -n XStatic-JQuery.quicksearch-2.0.3.1

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
